// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeCadastroAPI.Data;

#nullable disable

namespace SistemaDeCadastroAPI.Migrations
{
    [DbContext(typeof(SistemaCadastroDBContex))]
    partial class SistemaCadastroDBContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaDeCadastroAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(N'')");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaDeCadastroAPI.Models.ViagemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuarios");

                    b.Property<string>("NomeViagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("Viagem", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastroAPI.Models.ViagemModel", b =>
                {
                    b.HasOne("SistemaDeCadastroAPI.Models.UsuarioModel", "IdUsuariosNavigation")
                        .WithMany("Viagems")
                        .HasForeignKey("IdUsuarios")
                        .IsRequired()
                        .HasConstraintName("fk_usuarios");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("SistemaDeCadastroAPI.Models.UsuarioModel", b =>
                {
                    b.Navigation("Viagems");
                });
#pragma warning restore 612, 618
        }
    }
}
